# Music IA Education

## Coleta de Dados

- Quetionário via Google Forms
- Perguntas sobre a faixa etária, professor e estilo músical

## Objetivo do Experimento
- Criar músicas com ritmos e estilos músicais adequados para uma turma específica.
- As músicas tem objetivo de auxiliar o professor como recurso didático, sendo que as letras das canções abordarão um conteúdo ministrado pelo professor.
- As músicas serão geradas por IA no software SUNO e disponibilizadas em forma de link.

In [1]:
# Importar o pandas
import pandas as pd

In [3]:
df = pd.read_csv('datasets/pesquisamusicalv2.csv')

In [4]:
df.head()

,Carimbo de data/hora,Avalie os estilos musicais [rock],Avalie os estilos musicais [hip hop],Avalie os estilos musicais [mpb],Avalie os estilos musicais [reggae],Avalie os estilos musicais [funk],Avalie os estilos musicais [sertanejo],Avalie os estilos musicais [gospel],Avalie os estilos musicais [eletrônica],Qual professor,Qual sua faixa etária
0,21/08/2024 10:03:25,3,1,1,1,1,1,1,3,NaN,NaN
1,21/08/2024 10:04:39,5,3,5,2,1,3,1,5,NaN,NaN
2,21/08/2024 10:04:52,1,5,1,1,1,1,1,5,NaN,NaN
3,21/08/2024 10:04:53,1,5,4,4,4,1,1,5,NaN,NaN
4,21/08/2024 10:04:55,5,4,3,4,1,1,2,5,NaN,NaN

In [ ]:
df.colums = ['data_hora','rock', 'hip-hop','mpb','reggae', 'funk', 'sertanejo', 'gospel', 'eletronica','professor','faixa_etaria']

In [6]:
df.head()

,Carimbo de data/hora,Avalie os estilos musicais [rock],Avalie os estilos musicais [hip hop],Avalie os estilos musicais [mpb],Avalie os estilos musicais [reggae],Avalie os estilos musicais [funk],Avalie os estilos musicais [sertanejo],Avalie os estilos musicais [gospel],Avalie os estilos musicais [eletrônica],Qual professor,Qual sua faixa etária
0,21/08/2024 10:03:25,3,1,1,1,1,1,1,3,NaN,NaN
1,21/08/2024 10:04:39,5,3,5,2,1,3,1,5,NaN,NaN
2,21/08/2024 10:04:52,1,5,1,1,1,1,1,5,NaN,NaN
3,21/08/2024 10:04:53,1,5,4,4,4,1,1,5,NaN,NaN
4,21/08/2024 10:04:55,5,4,3,4,1,1,2,5,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Carimbo de data/hora                     95 non-null     object
 1   Avalie os estilos musicais [rock]        95 non-null     int64
 2   Avalie os estilos musicais [hip hop]     95 non-null     int64
 3   Avalie os estilos musicais [mpb]         95 non-null     int64
 4   Avalie os estilos musicais [reggae]      95 non-null     int64
 5   Avalie os estilos musicais [funk]        95 non-null     int64
 6   Avalie os estilos musicais [sertanejo]   95 non-null     int64
 7   Avalie os estilos musicais [gospel]      95 non-null     int64
 8   Avalie os estilos musicais [eletrônica]  95 non-null     int64
 9   Qual professor                           57 non-null     object
 10  Qual sua faixa etária                    57 non-null     object
dtypes: int64(8), object(3)
memory usage: 8.3+ KB

In [8]:
df.describe()

,Avalie os estilos musicais [rock],Avalie os estilos musicais [hip hop],Avalie os estilos musicais [mpb],Avalie os estilos musicais [reggae],Avalie os estilos musicais [funk],Avalie os estilos musicais [sertanejo],Avalie os estilos musicais [gospel],Avalie os estilos musicais [eletrônica]
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,3.263158,3.084211,3.242105,2.578947,2.431579,2.884211,2.652632,3.189474
std,1.545140,1.534450,1.396925,1.411043,1.492197,1.457652,1.493022,1.573009
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,1.500000,2.000000,1.000000,1.000000,1.500000,1.000000,1.000000
50%,4.000000,3.000000,4.000000,2.000000,2.000000,3.000000,2.000000,4.000000
75%,5.000000,4.500000,4.000000,3.500000,4.000000,4.000000,4.000000,5.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

23/08
- Visualizar os estilos por professor
- Criar gáfico pizza
- Criar grafico de barra colorida, com rotulos(figura)
- Storytelling
- A brincadeira dos 7 erros (brinde do grupo)
- Grafico de linhas (tudo) [segunda-feira]